const AppConstants = {
  LIMIT_DEFAULT_VALUE: 20,
  OFFSET_DEFAUKT_VALUE: 0,
  DB_URL: '127.0.01:27017/mic',
  USERNAME_MIN_LENGTH: 4,
  USERNAME_MAX_LENGTH: 20,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 24,
  EMAIL_MIN_LENGTH: 6,
  EMAIL_MAX_LENGTH: 30,
  NAME_MIN_LENGTH: 4,
  NAME_MAX_LENGTH: 50,
  AGE_MIN_VALUE:14,
  AGE_MAX_VALUE:101,
}

module.exports = AppConstants;
